//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALTTPR_Ladder
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ALTTPR_LadderEntities1 : DbContext
    {
        public ALTTPR_LadderEntities1()
            : base("name=ALTTPR_LadderEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_api_requests> tb_api_requests { get; set; }
        public virtual DbSet<tb_branches> tb_branches { get; set; }
        public virtual DbSet<tb_browse_logs> tb_browse_logs { get; set; }
        public virtual DbSet<tb_decay> tb_decay { get; set; }
        public virtual DbSet<tb_entrants> tb_entrants { get; set; }
        public virtual DbSet<tb_flags> tb_flags { get; set; }
        public virtual DbSet<tb_invitational_pairings> tb_invitational_pairings { get; set; }
        public virtual DbSet<tb_invitational_participants> tb_invitational_participants { get; set; }
        public virtual DbSet<tb_invitationals> tb_invitationals { get; set; }
        public virtual DbSet<tb_logs> tb_logs { get; set; }
        public virtual DbSet<tb_processes> tb_processes { get; set; }
        public virtual DbSet<tb_racers> tb_racers { get; set; }
        public virtual DbSet<tb_rankings> tb_rankings { get; set; }
        public virtual DbSet<tb_rankings_cache> tb_rankings_cache { get; set; }
        public virtual DbSet<tb_schedule> tb_schedule { get; set; }
        public virtual DbSet<tb_seed_tracking> tb_seed_tracking { get; set; }
        public virtual DbSet<tb_seeds> tb_seeds { get; set; }
        public virtual DbSet<tb_spoilers> tb_spoilers { get; set; }
        public virtual DbSet<tb_gainpercentages> tb_gainpercentages { get; set; }
        public virtual DbSet<tb_races> tb_races { get; set; }
    
        public virtual int sp_CalculateRaces()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CalculateRaces");
        }
    
        public virtual int sp_CacheRankings(Nullable<int> flag_id)
        {
            var flag_idParameter = flag_id.HasValue ?
                new ObjectParameter("flag_id", flag_id) :
                new ObjectParameter("flag_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CacheRankings", flag_idParameter);
        }
    
        public virtual int sp_CalculateRankings(Nullable<int> race_id)
        {
            var race_idParameter = race_id.HasValue ?
                new ObjectParameter("race_id", race_id) :
                new ObjectParameter("race_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CalculateRankings", race_idParameter);
        }
    
        public virtual int sp_ProcessDecay(Nullable<int> flag_id)
        {
            var flag_idParameter = flag_id.HasValue ?
                new ObjectParameter("flag_id", flag_id) :
                new ObjectParameter("flag_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ProcessDecay", flag_idParameter);
        }
    }
}
