//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALTTPR_Ladder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_api_requests
    {
        public int request_id { get; set; }
        public string Request { get; set; }
        public string IPAddress { get; set; }
        public System.DateTime RequestDateTime { get; set; }
    }
}
