//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALTTPR_Ladder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_decay
    {
        public int decay_id { get; set; }
        public int racer_id { get; set; }
        public int flag_id { get; set; }
        public int DecayAccrued { get; set; }
        public System.DateTime LastUpdated { get; set; }
    }
}
