//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALTTPR_Ladder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_entrants
    {
        public int entrant_id { get; set; }
        public int race_id { get; set; }
        public int racer_id { get; set; }
        public int FinishTime { get; set; }
        public System.DateTime DateTimeEntered { get; set; }
        public Nullable<System.DateTime> DateTimeFinished { get; set; }
        public string Comments { get; set; }
    }
}
