//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALTTPR_Ladder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_flags
    {
        public int flag_id { get; set; }
        public string FlagName { get; set; }
        public string FlagString { get; set; }
        public int branch_id { get; set; }
        public bool IsMystery { get; set; }
        public bool IsSpoiler { get; set; }
        public bool IsInvitational { get; set; }
        public bool IsGrabBag { get; set; }
        public int HoursToComplete { get; set; }
    }
}
