//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALTTPR_Ladder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_invitational_participants
    {
        public int participant_id { get; set; }
        public int invitational_id { get; set; }
        public int racer_id { get; set; }
        public string RaceTimeGG { get; set; }
        public int Seed { get; set; }
        public bool SendTrackerCode { get; set; }
    }
}
