//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALTTPR_Ladder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_invitational_pairings
    {
        public int pairing_id { get; set; }
        public int invitational_id { get; set; }
        public string PairingID { get; set; }
        public int Week { get; set; }
        public string GroupName { get; set; }
        public int participant1_id { get; set; }
        public int participant2_id { get; set; }
        public Nullable<int> Participant1Time { get; set; }
        public Nullable<int> Participant2Time { get; set; }
        public Nullable<System.DateTime> RaceDateTime { get; set; }
        public bool ThreadOpened { get; set; }
        public string RaceRoom { get; set; }
        public bool RaceFinished { get; set; }
        public string Participant1TrackingKey { get; set; }
        public string Participant1RestreamKey { get; set; }
        public string Participant2TrackingKey { get; set; }
        public string Participant2RestreamKey { get; set; }
        public Nullable<int> flag_id { get; set; }
        public string EventID { get; set; }
        public bool NeedsUpdates { get; set; }
        public bool HasRestream { get; set; }
    }
}
