//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALTTPR_Ladder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_processes
    {
        public int process_id { get; set; }
        public System.DateTime ProcessStart { get; set; }
        public Nullable<System.DateTime> ProcessEnd { get; set; }
        public string Messages { get; set; }
    }
}
