//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALTTPR_Ladder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_racers
    {
        public int racer_id { get; set; }
        public Nullable<int> old_racer_id { get; set; }
        public System.Guid RacerGUID { get; set; }
        public string RacerName { get; set; }
        public string RacerLogin { get; set; }
        public string DiscordID { get; set; }
        public bool IsActive { get; set; }
        public string StreamURL { get; set; }
    }
}
