//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALTTPR_Ladder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_races
    {
        public int race_id { get; set; }
        public System.Guid RaceGUID { get; set; }
        public int flag_id { get; set; }
        public Nullable<int> grabbag_id { get; set; }
        public int Schedule { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public Nullable<System.DateTime> RaceStartTime { get; set; }
        public string SeedURL { get; set; }
        public string MysteryJSON { get; set; }
        public bool HasStarted { get; set; }
        public bool HasCompleted { get; set; }
        public Nullable<bool> HasBeenProcessed { get; set; }
        public bool ChampionshipRace { get; set; }
    }
}
