//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALTTPR_Ladder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_rankings_cache
    {
        public int cache_id { get; set; }
        public int flag_id { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public int racer_id { get; set; }
        public string RacerName { get; set; }
        public int Ranking { get; set; }
        public int Rank { get; set; }
        public int GainLoss { get; set; }
        public int TotalRaces { get; set; }
        public int Firsts { get; set; }
        public int Seconds { get; set; }
        public int Thirds { get; set; }
        public int Forfeits { get; set; }
    }
}
