//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALTTPR_Ladder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_schedule
    {
        public int schedule_id { get; set; }
        public int flag_id { get; set; }
        public int ScheduleGroup { get; set; }
        public int SeedOrder { get; set; }
    }
}
